### ISSUE TITLE
User Roles within Postgres Database

### ISSUE THREAD

**Issue by TaraWilliamsPGH** [CMSgov/cms-carts-seds#206]
![user roles.PNG](https://images.zenhubusercontent.com/5f2069da63dfc750bb46f86f/7f7dd437-34d4-4175-9c2f-6ccf123acab3)Setting up permissions, associations to states, etc.

AC:
- [x] Define various roles (Ex. state user; cms user [PO has same); administrator(DSCP, Help Desk and Application Team)]
  - [x] User roles defined in Django model.
  - [x] ~~Fixtures loaded so that a wider range of fake users are available via Django.~~ Not via fixtures, but yes.
  - [x] Okta auth in dev/staging environments assigns dev users to one of those roles rather than just to a state user role.
  - [x] Fake auth allows bypassing and specifying roles other than state user.
- [x] User profiles include identifying information (name, email used for CARTS), association to a state if applicable, and assigned role.
  - [x] Okta auth checks for job codes to verify that user is allowed to have the role that the DB thinks they should have.
  - [x] After the assignment to dev users described above works, check against and make available the data the DB has about the user.
- [x] CO and admin users can see various state information without having to log in again.
  - [x] Endpoints set up for per-state views.
  - [x] Primarily a matter of frontend routing, and of dissociating determining the user from loading the state data.
  - [x] Endpoints support querying by status.
  - [x] Backend endpoints have auth added so that state users cannot make backend requests to other states' data.

- [ ] ~~Define endpoint for front end to read user data~~ (moved to #481)

QA Testing Notes:
1. If I am a state user I cannot see the same level of detail as a CMS user (example)

**Comment by tadhg-ohiggins** [comment]
Addressed by #789 and #794.

**Comment by tadhg-ohiggins** [comment]
#789 is now in mdctcartsdev.cms.gov
EUA users with the `CARTS_Group_Dev` will be assigned a role that has no state but lets them view the three states we have data for, e.g. https://mdctcartsdev.cms.gov/views/sections/AK/2020/0 https://mdctcartsdev.cms.gov/views/sections/AZ/2020/0 and https://mdctcartsdev.cms.gov/views/sections/MA/2020/0 will show Section 0 for the three states without requiring logging in again.

There is currently no frontend UI for this.

There is also a `?dev=dev-admin` role that allows seeing all of the state info; this role needs to be renamed but is the CMS/DSCP role.

https://mdctcartsdev.cms.gov/userinfo shows the user info.

State users with access to one state cannot see other state data; this PR also adds the per-state permissions and groups that we will use for more or less all access.

**Comment by StephanieCoppel** [comment]
added user roles grid if this helps at all!

**Comment by jgillis1** [comment]
[DSCP PO Assignments as of Feb 2020](https://app.zenhub.com/files/226399669/5d968163-614b-430b-851e-7051ee0a4f0f/download)

I'm still missing 2 EUA IDs for the POs but this can get things rolling.
